### ISSUE TITLE
Import to an existing index

### ISSUE THREAD

**Issue by mmullerbr** [codingchili/excelastic#36] opened 2017-07-31 16:08 UTC
Hi, first of all, let me congratulate you for the tool! It is really good!

Now, lets move to my issue.. :)

I already have an index and I want to move content from my excel file to my index. My index has a specific mapping (index fields match excel collumn titles) and specific settings, such as a custom analyser.

When I set the index name to a index that doesnt exist, it creates the index for me and everyting works fine.

When I set the index name to my preexisting index, excelastic runs to the end, but I am not able to find the documents in the index (running a match_all query).

Any ideas?

**Comment by codingchili** [comment] 2017-07-31 16:38
Hello and thanks! 

Could you check the types of the fields is matching? For example importing the file into a new index and then comparing field types to the existing? 

Should not be a general issue to import to pre-existing indexes, I've done so myself without issues. There was a similar issue where the date field would not be recognized properly, and the items would import successfully but not appear in the index. This was fixed in 1.2.0.

How is the dates formatted in the excel file? Is the date field in the excel documents type-formatted?

**Comment by mmullerbr** [comment] 2017-07-31 19:00
Hi, 
The types should match (they are all strings - there is no date or other type of fields.), but excelastic is creating all of them as kewords and my custom index has kewords and strings.

By the way, I am on my first steps with ES, so I might be doing something wrong..

**Here is my custom mapping:**
{
  "index-test": {
    "mappings": {
      "transactions": {
        "properties": {
          "INCIDENT_FULL_DESC": {
            "type": "text",
            "fields": {
              "text": {
                "type": "text",
                "analyzer": "brazilian_analyzer"
              }
            }
          },
          "INCIDENT_ID": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "INCIDENT_SHORT_DESC": {
            "type": "text",
            "fields": {
              "text": {
                "type": "text",
                "analyzer": "brazilian_analyzer"
              }
            }
          },
          "SYMPTOM_DESC": {
            "type": "text",
            "fields": {
              "text": {
                "type": "text",
                "analyzer": "brazilian_analyzer"
              }
            }
          },
          "SYMPTOM_ID": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    }
  }
}

**Excelastic generated mapping**

{
  "import-test": {
    "mappings": {
      "transactions": {
        "properties": {
          "INCIDENT_FULL_DESC": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "INCIDENT_ID": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "INCIDENT_SHORT_DESC": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "SYMPTOM_DESC": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          },
          "SYMPTOM_ID": {
            "type": "text",
            "fields": {
              "keyword": {
                "type": "keyword",
                "ignore_above": 256
              }
            }
          }
        }
      }
    }
  }
}

When I run the match_all search I get my hits:

GET import-test/_search
{
  "query": {
    "match_all": {}
  }
}
Result:
![image](https://user-images.githubusercontent.com/19627134/28793286-e549e812-7608-11e7-8e44-ca138ef9ec2f.png)


But when I run Excelastic pointing to index-test. It "loads" my 1985 records:
![image](https://user-images.githubusercontent.com/19627134/28793167-8453a372-7608-11e7-8121-718007638b83.png)

And when I search for documents,

GET index-test/_search
{
  "query": {
    "match_all": {}
  }
}

 I get this:
{
  "took": 24,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 5,
    "max_score": 1,
    "hits": [
      {
        "_index": "index-test",
        "_type": "transactions",
        "_id": "AV2aA9bfcdS0-pr383c1",
        "_score": 1,
        "_source": {}
      },
      {
        "_index": "index-test",
        "_type": "transactions",
        "_id": "AV2aA9bfcdS0-pr383c2",
        "_score": 1,
        "_source": {}
      },
      {
        "_index": "index-test",
        "_type": "transactions",
        "_id": "AV2aA9bfcdS0-pr383c0",
        "_score": 1,
        "_source": {}
      },
      {
        "_index": "index-test",
        "_type": "transactions",
        "_id": "AV2aA9bfcdS0-pr383c3",
        "_score": 1,
        "_source": {}
      },
      {
        "_index": "index-test",
        "_type": "transactions",
        "_id": "AV2aA9bfcdS0-pr383c4",
        "_score": 1,
        "_source": {}
      }
    ]
  }
}

**Comment by codingchili** [comment] 2017-07-31 19:31
Thank you very much, I can see where the problem lies already. Custom mappings do not currently work as the field types are all submitted as "transaction". Works fine with the defaults, but will obviously fail when an user has specified a custom mapping. Hoping to get it fixed by tomorrow.

**Comment by codingchili** [comment] 2017-07-31 20:12
Added option to specify mapping name when importing files. Released as 1.2.2, let me know if it works for you.

**Comment by mmullerbr** [comment] 2017-07-31 21:09
Hi,

Got an error:
![image](https://user-images.githubusercontent.com/19627134/28798591-53832f66-761b-11e7-955c-151552462941.png)

**Comment by codingchili** [comment] 2017-07-31 21:29
Uploaded the wrong jar, try again.

**Comment by mmullerbr** [comment] 2017-08-01 01:08
It is working!

I ran the command line, passing the data file, index name and document type as parameters and then the browser was opened and I had to type all over again, and then select the file. I dont think opening the browser is the deafult behavior, but I dont need it - command line works fine! :)  I guess this feature could be optional. (BTW, will it prevent me running it on a linux terminal?)

**My commnad**: java -jar excelastic-1.2.2.jar data2load3.xlsx import-test incident

![image](https://user-images.githubusercontent.com/19627134/28804727-63814c02-763b-11e7-9e8f-020ec64e910d.png)

Back to the import problem: after providing the info requested by the web page, the command starts running. When it finishes the data import, it keeps the process locked (it is not terminating the program). Other comon issue is a timeout error during the import process (occours on the previous version as well)

Besides these minor issues, the import process was successful.

**Command status**
![image](https://user-images.githubusercontent.com/19627134/28804423-78a93452-7639-11e7-9365-e5d40ef66fbd.png)

Thank you very much!

Regars,

**Comment by codingchili** [comment] 2017-08-01 16:49
Hello, good to hear its somewhat working now.

When adding the mapping parameter I forgot to update the code that checks if the web interface should be displayed. Fixed so it's no longer started if 2 or 3 parameters are given. In a console environment the commandline import will work fine. 

The process is being locked only for the web interface, to allow more files to be submitted. If the commandline is being locked it might be caused by some parts failing to index properly (timing out). 

How long does it take to import the file? seems like the timeouts are printed if the whole import process takes longer than 30s, I never had this happen because my imports are blazing fast here.

changed the following in the pre-release for 1.2.2
- web interface does not start when more than one parameter is given.
- increased the overall import timeout from 30 seconds to 5 minutes.

**Comment by mmullerbr** [comment] 2017-08-02 14:43
HI, just downloaded the new file!

The browser is not showing up (tks! :)), but I am still getting the time out error (Timed out after waiting 30000(ms) for a reply) . My file contains over 3.5 records and lots of texts. 

![image](https://user-images.githubusercontent.com/19627134/28878978-3d4b9e74-7777-11e7-8783-f3efa6b12317.png)

**Comment by codingchili** [comment] 2017-08-02 17:01
Ah yes, this is because the import is using the commandline here. And the commandline uses a separate timeout, so I added the updated timeout there as well.. oops! Updated 1.2.2 again.

**Comment by ponten68** [comment] 2017-08-28 13:00
[Excelastic 1.2.1 timeout.txt](https://github.com/codingchili/parser-excel-elasticsearch/files/1256780/Excelastic.1.2.1.timeout.txt)

Hello, starting by giving you super cred for having created this software in the sprit of Elasticsearch, i.e. ready-to-use! It happens to do exactly what I was looking for at the moment and works right out of the box, saved my much time in my work. Rare that something just works like that!
Have the same timeout issue in 1.2.1, see attached log from elasticsearch as well, but guess the issue was fixed in 1.2.2... will have a try with that one later in the week.
However, all data are read into elastic, it continues after the error message. Just the GUI will report failure.

**Comment by codingchili** [comment] 2017-08-30 16:50
@ponten68 thanks for the feedback, glad it's working!

**Closed as completed** 2017-10-02 19:09 UTC
Labels: bug

**Comment by syiand** [comment] 2018-02-27 18:46
Hey, I am trying to parse a excel file with custom mapping but I have some problems. I already used your plugin (which is really great and thank you for taking the time to create it :smile: ) and it works fine when I just parse the excel file. What is the right way to create the custom mapping? 
I tried the following, but even though it tells me that the file was successfully indexed it's empty. 
```
PUT february-2018
{
  "settings": {
    "analysis": {
      "analyzer": {
        "titel_analyzer": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "german_stop",
            "snow",
            "120_limit_token",
            "german_normalization"
          ]
        },
        "beschreibung_analyzer": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": [
            "lowercase",
            "german_stop",
            "snow",
            "500_limit_token",
            "german_normalization"
          ]
        }
      },
      "filter": {
        "german_stop": {
          "type": "stop",
          "stopwords": "_german_"
        },
        "snow": {
          "type": "snowball",
          "language": "German2"
        },
        "120_limit_token": {
          "type": "limit",
          "max_token_count": 120
        },
        "500_limit_token": {
          "type": "limit",
          "max_token_count": 500
        }
      }
    }
  },
  "mappings": {
    "doc": {
      "properties": {
        "Titel": {
          "type": "text",
          "analyzer": "titel_analyzer",
          "search_analyzer": "titel_analyzer"
        },
        "Beschreibung": {
          "type": "text",
          "analyzer": "beschreibung_analyzer",
          "search_analyzer": "beschreibung_analyzer"
        },
        "Datum": {
          "type": "date", 
          "format": ["yyyy-MM-dd"]
        }
      }
    }
  }
}
```
Should I remove the PUT? Thank you in advance! :)

**Comment by akhiljimmy7** [comment] 2019-02-21 00:31
Hi, 
I was having a error while uploading files. For the first time it was fine, when I try uploading the next time it is failing.
I uploaded a excel last month with Index name as january-2019. And when I tried to add more data this month to the same index, excelastic itself is creating a index named february-2019. How can I upload it into the same index which is January-2019?
