### ISSUE TITLE
Index with Dash Not Working

### ISSUE THREAD

**Issue by askalee90** [codingchili/excelastic#91] opened 2020-10-13 08:04 UTC
No error message, unable to inspect anything in web dev tool.
Kibana dev tool: _count is 0
Indices, Doc count 0, Storage size 416B

Uploaded CSV and excel and return same behavior.

excelastic version: 1.3.7

**Comment by askalee90** [comment] 2020-10-15 14:27
Just found that index with "-" will not posted to elk.
Do you all have any solutions ?

**Comment by codingchili** [comment] 2020-12-20 11:40
Hello, I'm unable to reproduce this issue with excelastic-1.3.7 and Elasticsearch 7.10.1 

1. downloaded and started elasticsearch 7.10.1, no configuration changes.
2. download excelastic-1.3.7.jar and run with `java -jar <filename>`
3. open the web interface and upload csv file
4. success message shown.
5. verify count has been incremented http://localhost:9200/_count
6. verify index with dash/hyphen now exists http://localhost:9200/_cat/indices

test.csv
```
Column 1, Column 2, Column 3
cell 6.1, cell 6.2, cell 6.3
cell 7.1, cell 7.2, cell 7.3
```

Using the default index, "december-2020" as suggested by the web interface, step 6 gives the following result

from: http://localhost:9200/_cat/indices
```
yellow open december-2020 7Zcih7qfQ1SYkSrUQtpxLw 1 1 2 0 5.2kb 5.2kb
```
And the count has been incremented by 2.

* does the same file work when you use an index without a dash/hyphen?

**Comment by codingchili** [comment] 2022-10-17 19:40
closing, please reopen if this is still an issue.

**Closed as completed by codingchili** 2022-10-17 19:40 UTC
