### ISSUE TITLE
limit exceeded - memory usage for large excel files

### ISSUE THREAD

**Issue by ghost** [codingchili/excelastic#62] opened 2018-09-18 14:24 UTC
Hello,

I'm trying to upload a 60MB xlsx file with something like 610 000 rows but i have this error

`java.lang.OutOfMemoryError: GC overhead limit exceeded`

I saw that there is already a ticket on similar issues so i tried this

`java -jar -Xmx4G  excelastic-1.2.7.jar` as suggered but still the same issue.

And before i get this error in my terminal i can see this warning

`PM io.vertx.core.impl.BlockedThreadChecker
WARNING: Thread Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 3086 ms, time limit is 2000`

Do you know how i can fix this issues please ?
Thanks in advance

**Comment by codingchili** [comment] 2018-09-21 17:38
Hello, 

either split the excel file into smaller parts or assign even more memory. I can't say how much you will need. the issue is caused by the way apache POI works. It attempts to load the entire excel workbook into memory at once. While the file is only 60MB the memory requirements in-memory is increased by a large factor.

Would converting the excel file into CSV work for you? We are currently adding support for importing CSV files, which would support streaming from disk - this would eliminate memory issues altogether.

Otherwise we would need to consider alternatives to POI in the future.

Here is some information on "GC overhead limit exceeded" error.
https://www.baeldung.com/java-gc-overhead-limit-exceeded

best regards,

**Comment by codingchili** [comment] 2018-09-21 17:45
Maybe we could change the excel parser to use this instead:

https://svn.apache.org/repos/asf/poi/trunk/src/examples/src/org/apache/poi/xssf/eventusermodel/XLSX2CSV.java

This would convert one row at a time from the excel sheet into CSV.
Maybe this can be used instead of the Workbooks in POI. Needs to support both HSSF and XSSF.

See https://poi.apache.org/components/spreadsheet/limitations.html

**Comment by codingchili** [comment] 2020-12-20 13:47
Not changing the excel parser anytime soon, to import very large files use csv instead - as it uses memory mapping it supports file sizes beyond RAM limits. If files cannot be converted, please investigate if investing in more RAM would solve the issue. 

Alternatively submit a PR with a more efficient excel parser.

Closing this for now.

**Closed as completed by codingchili** 2020-12-20 13:47 UTC
Labels: enhancement
